# Generated by Django 4.2.6 on 2025-05-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperIgralci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_igralca', models.IntegerField()),
                ('placa', models.IntegerField()),
                ('starost', models.IntegerField()),
                ('visina', models.IntegerField()),
                ('potencial', models.CharField(max_length=255)),
                ('metIzSkoka', models.IntegerField()),
                ('razdaljaMeta', models.IntegerField()),
                ('zunajnaObramba', models.IntegerField()),
                ('vodenjeZoge', models.IntegerField()),
                ('prodiranje', models.IntegerField()),
                ('podajanje', models.IntegerField()),
                ('metPodKosem', models.IntegerField()),
                ('obrambaPodKosem', models.IntegerField()),
                ('skok', models.IntegerField()),
                ('blokade', models.IntegerField()),
                ('vzdrzljivost', models.IntegerField()),
                ('prostiMeti', models.IntegerField()),
            ],
            options={
                'db_table': 'igralci',
            },
        ),
        migrations.CreateModel(
            name='timeOfScraperCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.CharField(max_length=255)),
            ],
        ),
    ]
