# Generated by Django 4.2.6 on 2025-05-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timeofscrapercall',
            table='time_of_call',
        ),
    ]
